version: "3"
services:
    app:
        build:
            context: ./CheatHub
            dockerfile: Dockerfile
        container_name: 'app-cheathub'
        restart: "on-failure"
        expose: 
            - "8443"
        ports: 
            - 8443:8443
        environment:
            - SERVICIO_INTERNO_NAME=intserv
        depends_on: 
            - intserv
    intserv:
        build:
            context: ./servicioInternoCheatHub
            dockerfile: Dockerfile
        container_name: 'intserv-cheathub'
        restart: "on-failure"
        expose: 
            - "8080" 
       