version: "3"
services:
    app-1:
        build:
            context: ./CheatHub
            dockerfile: Dockerfile
        container_name: 'app-1'
        restart: "on-failure"
        expose: 
            - "8443"
        environment:
            - SERVICIO_INTERNO_NAME=intserv
        depends_on: 
            - intserv
    app-2:
        build:
            context: ./CheatHub
            dockerfile: Dockerfile
        container_name: 'app-2'
        restart: "on-failure"
        expose: 
            - "8443"
        
        environment:
            - SERVICIO_INTERNO_NAME=intserv
        depends_on: 
            - intserv
    intserv:
        build:
            context: ./servicioInternoCheatHub
            dockerfile: Dockerfile
        container_name: 'intserv-cheathub'
        restart: "on-failure"
        expose: 
            - "8080" 
            
    balanceador:
        build:
            context: ./haproxy
            dockerfile: Dockerfile
        container_name: 'balanceador-cheathub'
           
        ports: 
            - "80:80"
            - "443:443"
            - "8404:8404"
        restart: "on-failure"
        depends_on: 
            - app-1
            - app-2
       